### ISSUE TITLE
Gmail support?

### ISSUE THREAD

**Issue by TheodoreEhrenborg** [AidanWelch/ProgressiveImmersion#13]
This plugin is great! I use it for Mandarin.

It doesn't seem to work for gmail (I'm using Firefox). Is it possible to add this feature? Maybe gmail does something strange that makes this difficult

**Comment by AidanWelch** [comment]
Hi,

Thanks!  I'm glad you like the project.  You're right that Gmail is doing something weird- I think it must be to do with it only rendering after loading.  Unfortunately, I'm really busy right now, but will work on a fix as soon as I can.


Thanks for catching this

**Comment by AidanWelch** [comment]
Okay, it seems to be working in 0.8.7 after this change fc1e8b273a51e6eab4c4de8f8bcf027ebb97a546  I hope it's helpful!

**Comment by TheodoreEhrenborg** [comment]
Brilliant
