### ISSUE TITLE
Breaks JavaScript on almost every website, in some way

### ISSUE THREAD

**Issue by Knewb** [AidanWelch/ProgressiveImmersion#17]
Non-exhaustive examples I've found which are broken in the ~3 hours I've had this installed:

- Instacart.com category page won't load at all
- Streaming video (YouTube is already mentioned in another issue, but Twitch.tv streams fail to load video as well)
- Reddit.com RES previews for images and videos
- Even this github project fails to load properly

I wonder if the find/replace function is manipulating in-line javascript causing it to throw syntax errors? I'm not sure why else it would break every page.

I'm using it to learn Vietnamese, in case there's an edge case here.

**Comment by AidanWelch** [comment]
Yeah, I'm having a similar issue, with the new addition of the mutation observer, I will investigate

**Comment by AidanWelch** [comment]
Should be fixed in 7d7bf6f7ee3ac9dc08ba31eae95c4dad8418afa1

I made sure to immediately release in v0.8.9.  Hopefully this time the fix doesn't unmask a bigger one 😅
